# задачи на строки

# ЗАДАЧА 1
Даны две строки: s1 и s2 с одинаковым размером, проверьте, может ли
некоторая перестановка строки s1 “победить” некоторую перестановку
строки s2 или наоборот.
Строка x может “победить” строку y (обе имеют размер n), если x[i]> = y
[i] (в алфавитном порядке) для всех i от 0 до n-1.

In [1]:
from itertools import permutations


def can_win(s_attack, s_defend):
    for i in range(len(s_attack)):
        if s_attack[i] < s_defend[i]:
            return False
    return True


def all_combinations(s1_origin, s2_origin):
    arr_all_comb1 = [''.join(p) for p in permutations(s1_origin)]
    arr_all_comb2 = [''.join(p) for p in permutations(s2_origin)]
    for s1 in arr_all_comb1:
        for s2 in arr_all_comb2:
            if s1 != s2:
                if can_win(s1, s2) or can_win(s2, s1):
                    return True
    return False

# примеры работы

In [2]:
print(all_combinations('abe', 'acc'))
print(all_combinations('abc', 'xya'))

False
True


# ЗАДАЧА 2
Дана строка s, вернуть самую длинную полиндромную подстроку в s.

In [3]:
def isPalindrome(s):
    return s == s[::-1]


def longest_palindrome(s):
    s_longest_pal = ''
    length = len(s)
    arr_all_substrings = [s[i: j] for i in range(len(s))
           for j in range(i + 1, len(s) + 1)]

    for s1 in arr_all_substrings:
        if isPalindrome(s1):
            if len(s1) > len(s_longest_pal):
                s_longest_pal = s1
    return s_longest_pal

# примеры работы

In [5]:
s = 'babad'
print(longest_palindrome(s))
s = 'cbbd'
print(longest_palindrome(s))

bab
bb


# ЗАДАЧА 3
Вернуть количество отдельных непустых подстрок текста, которые могут
быть записаны как конкатенация некоторой строки с самой собой (т.е. она
может быть записана, как a + a, где a - некоторая строка).

In [6]:
from math import ceil


def concat(s):

    return s == s[:ceil(len(s) / 2)] + s[:ceil(len(s) / 2)]


def all_concat(s):
    dict_of_concat = dict()
    length = len(s)
    arr_all_substrings = [s[i: j] for i in range(length)
           for j in range(i + 1, length + 1)]

    for s1 in arr_all_substrings:
        if concat(s1):
            dict_of_concat.__setitem__(s1, 0)
    return len(dict_of_concat)

# примеры работы

In [7]:
s = 'abcabcabc'
print(all_concat(s))

3


# Задача «Объединение отрезков»
Дан массив отрезков intervals, в котором intervals[i] = [starti, endi], некоторые
отрезки могут пересекаться. Напишите функцию, которая объединяет все пересекающиеся отрезки
в один и возвращает новый массив непересекающихся отрезков.

In [1]:
def unite(intervals):
    j = 0
    while j < len(intervals):
        i = 0
        while i < len(intervals):
            if intervals[i][0] < intervals[j][1] and intervals[i][1] > intervals[j][0] and intervals[i] != intervals[j]:
                if intervals[i][0] <= intervals[j][0]:
                    intervals[j] = [intervals[i][0], intervals[j][1]]
                if intervals[i][1] >= intervals[j][1]:
                    intervals[j] = [intervals[j][0], intervals[i][1]]
                intervals.pop(i)

                i -= 1
                j -= 1
            i += 1
        j += 1

# примеры работы

In [2]:
intervals = [[1, 3], [2, 6], [8, 10], [15, 18]]

unite(intervals)

print(intervals)

[[1, 6], [8, 10], [15, 18]]


# Контрольные задачи 

# Задача 1. «Треугольник с максимальным периметром»
Массив A состоит из целых положительных чисел длин
отрезков. Составьте из трех отрезков
такой треугольник, чтобы его периметр был максимально возможным. Если невозможно
составить треугольник с положительной площадью функция
возвращает 0.

In [8]:
def puzir(arr):
    length = len(arr)
    for i in range(length-1):
        for j in range(length-i-1):
            if arr[j] < arr[j+1]:
                arr[j], arr[j+1] = arr[j+1], arr[j]
    return arr


def max_per(arr):
    length = len(arr)
    for i in range(length-2):
        if arr[i]+arr[i+1] > arr[i+2] and arr[i]+arr[i+2] > arr[i+1] and arr[i+2]+arr[i+1] > arr[i]:
            per = arr[i] + arr[i+1] + arr[i+2]
            return per
    return 0

# пример работы

In [9]:
arr = [2, 1, 2]
print(max_per(arr))

5


# Задача 2. «Максимальное число»
Дан массив неотрицательных целых чисел nums. Расположите их в таком порядке, чтобы
вместе они образовали максимально возможное число.

In [11]:
import numpy
from copy import deepcopy


def biggest_first_number(row):
    ans_row = deepcopy(row)

    max = -3
    for i in range(len(row)):
        if ans_row[i][0] >= max:
            max = ans_row[i][0]
    for i in range(len(row)):
        if ans_row[i][0] != max and ans_row[i][0] >= 0:
            ans_row[i][0] = -2
    return ans_row


def add_best_numbers(row, original_row):
    big_number = ''
    isNeededToBeChecked = False

    for i in range(len(row)):
        if row[i][0] >= 0:  
            if len(row[i]) == 1:
                big_number += str(''.join(map(str, original_row[i])))
                row[i][0] = -1
            else:
                row[i].__delitem__(0)
                isNeededToBeChecked = True

    length = len(row)
    i = 0
    while i < length:  # удаляем добавленные числа
        if row[i][0] == -1:
            original_row.__delitem__(i)
            row.__delitem__(i)
            length -= 1
        else:
            i += 1

    if isNeededToBeChecked:
        best_numbers = biggest_first_number(row)
        big_number += add_best_numbers(best_numbers, original_row)
    return big_number


def find_max(row):
    length = len(row)
    big_number = ''

    raw_row = [''] * length

    for i in range(length):
        number = str(row[i])  # превращаем наши числа в массив символов
        raw_row[i] = list(number)  # записываем наш массив в массив
        raw_row[i] = [int(raw_row[i]) for raw_row[i] in raw_row[i]]

    while len(raw_row) != 0:
        best_numbers = biggest_first_number(raw_row)  # находим лучших кандидатов

        big_number += add_best_numbers(best_numbers, raw_row)

    return big_number

# пример работы

In [19]:
row = numpy.random.randint(1, 150, size=5)
print(row)
result = find_max(row)
print(result)

[ 96  48   4  10 116]
9644811610


# Задача 3. «Сортировка диагоналей в матрице»
Дана матрица mat размером m * n, значения целочисленные.
Напишите функцию, сортирующую
каждую диагональ матрицы по возрастанию и возвращающую получившуюся матрицу.

In [13]:
import numpy

def sort_matrix(mat):
    height = len(mat)
    width = len(mat[0])

    for x_start in range(1, width):
        line = []
        x = x_start
        for y in range(height - (0 if width - height - x >= 0 else abs(width - height - x)) ):
            line.append(mat[y][x])
            x += 1
        #print(line)
        line.sort()
        #print(line)

        x = x_start
        for y in range(height - (0 if width - height - x >= 0 else abs(width - height - x)) ):
            mat[y][x] = line[y]
            x += 1

    for y_start in range(0, height):
        line = []
        y = y_start
        for x in range(width - (0 if height - width - y >= 0 else abs(height - width - y)) ):
            line.append(mat[y][x])
            y += 1
        #print(line)
        line.sort()
        #print(line)

        y = y_start
        for x in range(width - (0 if height - width - y >= 0 else abs(height - width - y)) ):
            mat[y][x] = line[x]
            y += 1

# пример работы

In [15]:
matrix = numpy.random.randint(0, 10, size=(5,4))
print(matrix)

sort_matrix(matrix)
print(matrix)

[[5 3 8 8]
 [8 9 5 0]
 [0 8 8 9]
 [7 8 1 6]
 [6 4 5 8]]
[[5 3 0 8]
 [1 6 5 8]
 [0 8 8 9]
 [4 5 8 9]
 [6 7 8 8]]
